---
title: "Passwordless ssh"
author: "mateen"
format:
  html:
    toc: true
number-sections: true
---

# Requirements {.unnumbered}
This assumes that you already know how to ssh in using your password so its all set up.

# Check if you have existing keys
If you unnecssarily create new keys, you'll have to copy the new keys to all of the existing computers that you use for passwordless ssh.

Look for a `.pub` file.

::: {.panel-tabset}
## Windows
```.bash
dir ~\.ssh\
```

## Mac/Linux
```.bash
ls ~/.ssh/
```

:::

If you have an existing `.pub` file, note its name and proceed directly to the step to [Copy keys to remote server](#sec-copykeys) . If you don't, then create keys as below.

## Create new keys

```.bash
ssh-keygen -t ed25519
```

There are different types/ways of keys to make. This is good enough. 

::: {.callout-note collapse="true"}
## Useless Dorky Note {.unnumbered}
You can look up other ways if you're very interested. The `-t ed25519` is fairly popular as of this article in 2025 because it works faster (but we're talking about a millisecond, though) than the old RSA standard (below) but gives about the same security. 

```.bash
ssh-keygen -t rsa -b 3072
```
The `-t rsa` makes the type follow the RSA scheme. `-b 3072` is the length of the key in binary/bits. 3072 bits is like a regular password  over 500 characters long. It has comparable to the security what the ed25519 provides, but is more efficient (again, it's only around a millisecond). However, RSA can be made more secure by using a larger number, typically $2^{12}=4096$ if desired.

:::

When prompted for the location to make the keys, accept the default location and press enter. You can enter a passphrase if you wish.

# Copy keys to remote server {#sec-copykeys}
Go to the folder containing the new keys (the `.pub` file). In the example below I'll assume its the default `id_rsa.pub`. If you noted a different name above, substitute it.

```.bash
cd ~\.ssh\
```

Copy the keys. You'll have to enter the password a last time. If you need to be on the vpn to ssh 
normally, then the vpn should be active now for this step. 

::: {.panel-tabset}
## Windows

```.bash
type id_rsa.pub | ssh username@haudenosaunee.tru.ca “mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys”
```

<!--
<code>type id_rsa.pub | ssh <span style="color: red;">username@haudenosaunee.tru.ca</span> \`<br>"mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"</code>
-->
where you must replace <code><span style="color: red;">username@haudenosaunee.tru.ca</span></code> with your username@host.

## Mac/Linux
```.bash
ssh-copy-id -i id_rsa.pub username@haudenosaunee.tru.ca
```

<!--<code>ssh-copy-id -i id_rsa.pub <span style="color: red;">username@haudenosaunee.tru.ca</span></code>
-->

where you must replace <code><span style="color: red;">username@haudenosaunee.tru.ca</span></code> with your username@host.

::: 

# Test

Now log in as per usual with ssh and you should be good to go